# Generated by Django 4.1.6 on 2024-07-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts_app", "0004_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
